import { Client, Session } from "@heroiclabs/nakama-js";

/**
 * Auth API — handles registration and login via Nakama RPCs.
 *
 * SECURITY DESIGN:
 * - A single reusable "bootstrap" device session is used for all auth RPCs.
 *   This prevents orphaned device accounts from accumulating.
 * - The server RPCs (rpcRegisterUser / rpcLoginUser) validate credentials
 *   and return a server-generated session token. The client NEVER calls
 *   client.authenticateCustom() — sessions are only issued by the server
 *   after password verification.
 */

let _client = null;
let _bootstrapSession = null;

const BOOTSTRAP_DEVICE_ID = "tictactoe_auth_bootstrap";

function getClient() {
  if (!_client) {
    const host = import.meta.env.VITE_NAKAMA_HOST;
    const port = import.meta.env.VITE_NAKAMA_PORT;
    const ssl = import.meta.env.VITE_NAKAMA_SSL === "true";
    const serverKey = import.meta.env.VITE_NAKAMA_SERVER_KEY;
    _client = new Client(serverKey, host, port, ssl);
  }
  return _client;
}

/**
 * Returns a reusable bootstrap session for calling auth RPCs.
 * Uses a single fixed device ID — no orphaned accounts created.
 */
async function getBootstrapSession() {
  if (_bootstrapSession && !_bootstrapSession.isexpired) {
    return _bootstrapSession;
  }
  const client = getClient();
  _bootstrapSession = await client.authenticateDevice(crypto.randomUUID(), true);
  return _bootstrapSession;
}

/**
 * Register a new user account.
 * The server creates the account, validates, and returns a session token.
 * @returns {{ success: boolean, userId?: string, username?: string, token?: string, error?: string }}
 */
export async function registerUser(username, password) {
  const client = getClient();
  const bootstrapSession = await getBootstrapSession();
  
  const result = await client.rpc(bootstrapSession, "register_user", { username, password });
  const data = typeof result.payload === "string" ? JSON.parse(result.payload) : result.payload;
  return data;
}

/**
 * Login with existing credentials.
 * The server validates the password and returns a server-generated session token.
 * The client NEVER calls authenticateCustom — the token is used directly.
 * @returns {{ session: Session, userId: string, username: string }} — throws on failure
 */
export async function loginUser(username, password) {
  const client = getClient();
  const bootstrapSession = await getBootstrapSession();
  
  const result = await client.rpc(bootstrapSession, "login_user", { username, password });
  const data = typeof result.payload === "string" ? JSON.parse(result.payload) : result.payload;
  
  if (!data.success) {
    throw new Error(data.error || "Login failed");
  }

  // Restore the server-generated token into a Session object.
  // The token was generated by nk.authenticateTokenGenerate() on the server
  // AFTER password validation — no client-side authenticateCustom needed.
  const session = Session.restore(data.token, "");
  
  return {
    session,
    userId: data.userId,
    username: data.username,
    token: data.token
  };
}

/**
 * Clear local auth state.
 */
export function logout() {
  localStorage.removeItem("auth_username");
  localStorage.removeItem("auth_session_token");
  localStorage.removeItem("auth_session_refresh_token");
  localStorage.removeItem("active_match_id");
}
